language: node_js

node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn build

notifications:
  email: false
# deploy:
#   provider: pages
#   local_dir: dist
#   skip_cleanup: true
#   target_branch: gh-pages
#   verbose: true
#   github_token: $GITHUB_TOKEN
#   email: $GITHUB_EMAIL
#   name: $GITHUB_USERNAME
#   keep_history: true
#   on:
#     branch: master
