language: node_js

node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - ./node_modules/.bin/tsc --project .webpack --outDir .webpack

notifications:
  email: false
