export enum LOGIN {
    REQUEST = "LOGIN_REQUEST",
    SUCCESS = "LOGIN_SUCCESS",
    FAILURE = "LOGIN_FAILURE",
}

export enum LOGOUT {
    REQUEST = "LOGOUT_REQUEST",
    SUCCESS = "LOGOUT_SUCCESS",
    FAILURE = "LOGOUT_FAILURE",
}
